import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/Header";
import Footer from "../components/Footer";
import QuestionsProvider from "../contexts/QuestionsProvider";
import PersonalizeProvider from "@/contexts/PersonalizeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={inter.className}>
        <QuestionsProvider>
          <PersonalizeProvider>
            <Header />
            <div className="rootContent">{children}</div>
            <Footer />
          </PersonalizeProvider>
        </QuestionsProvider>
      </body>
    </html>
  );
}
